# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            None
tagline:          'Test'
description:      'Made by me'
url:              http://none
baseurl:          /

author:
  name:           'Me'
  url:            https://none

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
